name: CordCloud2

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.COMPANY_CC_EMAIL }}
          passwd: ${{ secrets.COMPANY_CC_PASSWD }}
