name: V2ex

on:
  schedule:
    - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/v2ex-action@main
        with:
          webhook: ${{secrets.WEBHOOK}}
          count: 10
